// <auto-generated />
namespace server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
<<<<<<<< HEAD:server/Migrations/202303251624247_initall.Designer.cs
    public sealed partial class initall : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initall));
        
        string IMigrationMetadata.Id
        {
            get { return "202303251624247_initall"; }
========
    public sealed partial class init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init));
        
        string IMigrationMetadata.Id
        {
            get { return "202303260453427_init"; }
>>>>>>>> origin/dev:server/Migrations/202303260453427_init.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
